_BASE_: "Base.yaml"
MODEL:
  META_ARCHITECTURE: "PSONet"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  IMS_PER_BATCH: 16
OUTPUT_DIR: ./train_log/0925_psonet_v1